hadoop-hdfs-project/hadoop-hdfs/src/main/resources/ssm-default.xml
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/SSMConfigureKeys.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/SSMServer.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/protocol/ClientSSMProtocol.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/protocol/SSMClient.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/protocol/SSMServiceState.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/protocol/SSMServiceStates.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/protocolPB/ClientSSMProtocolClientSideTranslatorPB.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/protocolPB/ClientSSMProtocolPB.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/protocolPB/ClientSSMProtocolServerSideTranslatorPB.java
hadoop-ssm-project/src/main/proto/clientSSM.proto
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/TestSSMClient.java

ssmRpcServer code format and single ssmServer

ssmRpcServer code format and single ssmServer

---

hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/sql/DBAdapter.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/sql/StoragePolicy.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/sql/Util.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/sql/TestDBMethod.java

1.add insertStorageTables() updateStoragesTable() and getStorageCapacity() to insert, update and retrieve info from table 'storages' in DBAdapter
2.add testInsertStorageTables() to test insert, update and retrieve info
3.add insertStoragePolicyTable(), getStoragePolicyName() and getStoragePolicyID() to insert and retrieve info from table 'storage_policy' in DBAdapter
4.add test method testInsertStoragePolicyTable() to test insert and retrieve info

#81 Implement interface to operate table 'storages' and 'storage_policy'

---

.travis.yml

fix #92 enable travis for ssm module

---

hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/sql/DBAdapter.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/sql/TestDBMethod.java

1.add insertCachedFiles(long fid, long fromTime,
long lastAccessTime, int numAccessed) insertCachedFiles(List<CachedFileStatus> s) 
2.add updateCachedFiles()

#89 Implement interfaces to operate table 'cached_files'

---

hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/actions/MoveFile.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/sql/DBAdapter.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/actions/MoveToArchiveTest.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/actions/MoveToSSDTest.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/sql/TestDBMethod.java

- Update command status according to cid, rid and state.
- Add Unit Test in TestDBMethod.

Add Update Command Status in DBAdapter

---

hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/Command.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/CommandExecutor.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/sql/CommandInfo.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/CommandExecutorTest.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/actions/MoveToArchiveTest.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/actions/MoveToCacheTest.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/actions/MoveToSSDTest.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/sql/TestDBMethod.java

- Basic methods of CommandExecutor
- Unit Test of CommandExecutor
- Callback for Command

Finish basic methods and Unit Test of CommandExecutor

---

hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/sql/DBAdapter.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/sql/Util.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/sql/TestDBMethod.java

1.add insertXattrTable() and getXattrTable()
2.add testInsertXattrTable()

#98 Implement interface to operate table 'xattr'

---

hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/Command.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/CommandExecutor.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/actions/MoveFile.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/actions/MoveToCache.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/CommandExecutorTest.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/actions/MoveToCacheTest.java

Fix a bug caused by "_FILE_PATH_".
Fix a bug caused by ActionType.
Fix a bug caused by cache sync.
Add batch Command Status update.

Fix bugs in CommandExecutor

---

hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/Command.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/CommandExecutor.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/CommandExecutorTest.java

Fix a bug caused by command queue(cmdInState).
Fix a bug in ThreadGroup, which may cause unexpected destory.
Fix a bug in Unit Case, which may caused "file not found".
Enhance UT support with SSM Server.

Fix multi-thread problem in CommandExecutor.

---

hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/Command.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/CommandExecutor.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/actions/ActionBase.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/actions/ActionExecutor.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/TestCommandExecutor.java

Integrate with new Mover.
Fix a bug in CommandExecutor UT.

Integrate with new Mover

---

hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/Command.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/TestCommand.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/TestCommandExecutor.java

Add Command Unit Test for Actions and Mover.
Refactor CommandExecutor UT.

Add Command Unit Test

---

hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/Command.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/CommandExecutor.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/TestCommand.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/TestCommandExecutor.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/TestEmptyMiniSSMCluster.java

Add more storage types for SSMServer Unit Test.
Fix a bug caused by "pool" thread.
Refactor Command and CommandExecutor UT

Add more storage types for SSMServer Test

---

hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/mover/MoverPool.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/mover/MoverStatus.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/mover/TestMoverPool.java

Add some log and add shutdown interface

#127 Improve status tracking and process control of Mover tool

---

hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/Command.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/CommandExecutor.java
hadoop-ssm-project/src/main/java/org/apache/hadoop/ssm/CommandPool.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/TestCommand.java
hadoop-ssm-project/src/test/java/org/apache/hadoop/ssm/TestCommandPool.java

Replace ThreadGroup with CommandPool.
Refactor Command and CommandPool.
Refactor Command and CommandPool UT.

Fix a deadlock caused by ThreadGroup.

---

hadoop-smart-project/src/main/java/org/apache/hadoop/smart/CommandExecutor.java
hadoop-smart-project/src/main/java/org/apache/hadoop/smart/CommandState.java
hadoop-smart-project/src/main/java/org/apache/hadoop/smart/SmartRpcServer.java
hadoop-smart-project/src/main/java/org/apache/hadoop/smart/protocol/ClientSSMProtocol.java
hadoop-smart-project/src/main/java/org/apache/hadoop/smart/protocol/SmartClient.java
hadoop-smart-project/src/main/java/org/apache/hadoop/smart/protocolPB/ClientSmartProtocolClientSideTranslatorPB.java
hadoop-smart-project/src/main/java/org/apache/hadoop/smart/sql/CommandInfo.java
hadoop-smart-project/src/main/java/org/apache/hadoop/smart/sql/DBAdapter.java
hadoop-smart-project/src/test/java/org/apache/hadoop/smart/TestCommandExecutor.java

submitCommand for command submit.
getCommandInfo for getting commandinfo with given commandID.
listCommandinfs for getting all commands executing.
activateCommand for activating(insert it to queue) an given command.
deleteCommand for delete a command from queue, if this command is running, then kill it.

Add CommandRPC support

---

hadoop-smart-project/src/main/java/org/apache/hadoop/smart/mover/Mover.java
hadoop-smart-project/src/test/java/org/apache/hadoop/smart/mover/TestMover.java
hadoop-smart-project/src/test/java/org/apache/hadoop/smart/mover/TestMoverPool.java

This PR is for branch refactor

Refactor Mover to Hadoop 2.7.3

---

smart-server/src/main/java/org/apache/hadoop/smart/Command.java
smart-server/src/main/java/org/apache/hadoop/smart/CommandExecutor.java
smart-server/src/main/java/org/apache/hadoop/smart/CommandPool.java
smart-server/src/main/java/org/apache/hadoop/smart/actions/MoveFile.java
smart-server/src/main/java/org/apache/hadoop/smart/actions/MoveToCache.java
smart-server/src/test/java/org/apache/hadoop/smart/TestCommand.java
smart-server/src/test/java/org/apache/hadoop/smart/TestCommandExecutor.java
smart-server/src/test/java/org/apache/hadoop/smart/TestCommandPool.java
smart-server/src/test/java/org/apache/hadoop/smart/actions/TestMoveToArchive.java
smart-server/src/test/java/org/apache/hadoop/smart/actions/TestMoveToCache.java
smart-server/src/test/java/org/apache/hadoop/smart/actions/TestMoveToSSD.java

Fix a bug caused by single instance.
Fix a bug in UT.
Code style and imports.

Merge Command_Refactor

---

smart-server/src/main/dashboard/views/rules/rule/rule.html
smart-server/src/main/java/org/smartdata/server/actions/mover/defaultmover/Mover.java
smart-server/src/main/java/org/smartdata/server/actions/mover/defaultmover/MoverCli.java
smart-server/src/main/java/org/smartdata/server/actions/mover/defaultmover/MoverProcessor.java
smart-server/src/main/java/org/smartdata/server/actions/mover/defaultmover/MoverStatus.java
smart-server/src/test/java/org/smartdata/server/actions/mover/TestMoverPool.java
smart-server/src/test/java/org/smartdata/server/actions/mover/defaultmover/TestMover.java

Refine percentage information of Mover

#127 Improve status tracking and process control of Mover tool 

---

smart-server/src/main/java/org/smartdata/server/actions/ActionRegister.java
smart-server/src/main/java/org/smartdata/server/actions/mover/MoverPool.java
smart-server/src/main/java/org/smartdata/server/command/Command.java
smart-server/src/main/java/org/smartdata/server/command/CommandExecutor.java
smart-server/src/main/java/org/smartdata/server/command/CommandPool.java
smart-server/src/test/java/org/smartdata/server/actions/TestActionRegister.java
smart-server/src/test/java/org/smartdata/server/command/TestCommandExecutor.java
smart-server/src/test/java/org/smartdata/server/metastore/sql/TestDBMethod.java

Fix a issue caused by MoverPool.removeStatus.
Reduce the running time of TestcommandExecutor.
Fix a issue caused by ActionRegister singleInstance.
Remove/Modify UT logs.

Enhance Command related UT, reduce running time.

---

smart-actions/src/main/java/org/smartdata/actions/hdfs/CacheFileAction.java
smart-server/src/main/java/org/smartdata/server/command/Command.java
smart-server/src/main/java/org/smartdata/server/command/CommandPool.java
smart-server/src/test/java/org/smartdata/server/command/TestCommand.java
smart-server/src/test/java/org/smartdata/server/command/TestCommandPool.java

* Fix Command
* Fix CommandPool
* Temporarily fix CacheStatus.

Fix Command and CommandPool

---

smart-actions/src/main/java/org/smartdata/actions/hdfs/CacheFileAction.java
smart-server/src/main/java/org/smartdata/server/command/Command.java
smart-server/src/main/java/org/smartdata/server/command/CommandExecutor.java
smart-server/src/test/java/org/smartdata/server/command/TestCommand.java
smart-server/src/test/java/org/smartdata/server/command/TestCommandExecutor.java

* Fix commandExecutor
* Reduce move file actions in UT

Fix command executor

---

smart-server/src/main/java/org/smartdata/server/command/CommandDescriptor.java
smart-server/src/main/java/org/smartdata/server/command/CommandExecutor.java
smart-server/src/test/java/org/smartdata/server/command/TestCommand.java
smart-server/src/test/java/org/smartdata/server/command/TestCommandExecutor.java
smart-server/src/test/java/org/smartdata/server/command/TestCommandPool.java

* Fix submitCommand.
* Add createFromParameters.

Fix submitCommand

---

smart-actions/src/main/java/org/smartdata/actions/ActionRegistry.java
smart-actions/src/main/java/org/smartdata/actions/SmartAction.java
smart-common/src/main/java/org/smartdata/common/actions/ActionInfo.java
smart-common/src/main/java/org/smartdata/common/actions/ActionInfoComparator.java
smart-server/src/main/java/org/smartdata/server/command/CommandExecutor.java
smart-server/src/main/java/org/smartdata/server/command/CommandPool.java
smart-server/src/main/java/org/smartdata/server/metastore/DBAdapter.java
smart-server/src/test/java/org/smartdata/server/command/TestCommandExecutor.java

* Fix submitCommand.
* Add listActions.
* Add listActionSupported.
* Add CommandExecutor API UTs.

Command Executor API fix

---

smart-actions/src/main/java/org/smartdata/actions/ActionStatus.java
smart-actions/src/main/java/org/smartdata/actions/hdfs/move/MoverBasedMoveRunner.java
smart-common/src/main/java/org/smartdata/common/actions/ActionInfo.java
smart-server/src/main/java/org/smartdata/server/command/CommandExecutor.java
smart-server/src/test/java/org/smartdata/server/command/TestCommand.java
smart-server/src/test/java/org/smartdata/server/command/TestCommandPool.java

* Remove UUID in actions.
* Add getActionInfo.

Remove UUID in all actions

---

smart-actions/src/test/java/org/smartdata/actions/hdfs/ActionMiniCluster.java

add license

---

smart-server/src/main/java/org/smartdata/server/metastore/DBAdapter.java
smart-server/src/main/java/org/smartdata/server/metric/fetcher/CachedListFetcher.java
smart-server/src/test/java/org/smartdata/server/metastore/TestDBMethod.java
smart-server/src/test/java/org/smartdata/server/metric/fetcher/TestCachedListFetcher.java

* Get fids from `files` table.
* Sync fids with fileSet, which fetches fids from DB during initialization.

Fix wrong fid problem.

---

smart-common/src/main/java/org/smartdata/common/CommandState.java
smart-server/src/main/java/org/smartdata/server/command/Command.java
smart-server/src/main/java/org/smartdata/server/command/CommandExecutor.java
smart-server/src/test/java/org/smartdata/server/command/TestCommandExecutor.java

* Fix Exceptions throws by actions.
* Fix wrong command problem.

Fix a bug caused by wrong command and wrong actions.

---

smart-actions/src/main/java/org/smartdata/actions/SmartAction.java
smart-actions/src/main/java/org/smartdata/actions/hdfs/CacheFileAction.java
smart-server/src/main/java/org/smartdata/server/command/Command.java
smart-server/src/main/java/org/smartdata/server/command/CommandExecutor.java
smart-server/src/main/java/org/smartdata/server/metastore/DBAdapter.java
smart-server/src/test/java/org/smartdata/server/command/TestCommandExecutor.java
smart-server/src/test/java/org/smartdata/server/metastore/TestDBMethod.java

* Maintenance command id.
* Add command check during submit.
* Write actions to DB after command is inserted.
* Update Actions after Command is finished. 
* Move action.init to command and catch all exceptions during execution.
* Add logs for cachefileAction.

Fix submitcommand and CommandInfo

---

smart-actions/src/main/java/org/smartdata/actions/SmartAction.java
smart-actions/src/main/java/org/smartdata/actions/hdfs/CacheFileAction.java
smart-common/src/main/java/org/smartdata/common/command/CommandInfo.java
smart-common/src/main/java/org/smartdata/common/protocolPB/PBHelper.java
smart-common/src/main/proto/AdminServer.proto
smart-server/src/main/java/org/smartdata/server/SmartRpcServer.java
smart-server/src/main/java/org/smartdata/server/command/Command.java
smart-server/src/main/java/org/smartdata/server/command/CommandExecutor.java
smart-server/src/main/java/org/smartdata/server/metastore/DBAdapter.java
smart-server/src/main/java/org/smartdata/server/metastore/Util.java
smart-server/src/main/scala/org/smartdata/server/web/RuleService.scala
smart-server/src/test/java/org/smartdata/server/TestSmartAdmin.java
smart-server/src/test/java/org/smartdata/server/command/TestCommandExecutor.java
smart-server/src/test/java/org/smartdata/server/metastore/TestDBMethod.java

* Maintenance command id.
* Add command check during submit.
* Write actions to DB after command is inserted.
* Update Actions after Command is finished. 
* Move action.init to command and catch all exceptions during execution.
* Add logs for cachefileAction.

CommandInfo and CommandExecutor Enhance

---

smart-actions/src/main/java/org/smartdata/actions/hdfs/WriteFileAction.java
smart-server/src/main/java/org/smartdata/server/command/CommandExecutor.java
smart-server/src/main/java/org/smartdata/server/metastore/DBAdapter.java
smart-server/src/main/java/org/smartdata/server/metric/fetcher/CachedListFetcher.java
smart-server/src/test/java/org/smartdata/server/metric/fetcher/TestCachedListFetcher.java

* Fix cache list empty issue.
* Add error message to writeFileAction.

Fix cache list empty issue. 

---

smart-server/src/main/java/org/smartdata/server/metastore/DBAdapter.java
smart-server/src/main/java/org/smartdata/server/metric/fetcher/CachedListFetcher.java
smart-server/src/test/java/org/smartdata/server/metric/fetcher/TestCachedListFetcher.java

* Fix `uncache file still in list` issue.
* Add new test cases.
* Add fault tolerant for exception and recovery.

Fix uncache problem, and add fault tolerant.

---

smart-server/src/main/java/org/smartdata/server/command/CommandExecutor.java
smart-server/src/test/java/org/smartdata/server/command/TestCommandExecutor.java

* Add file lock in current running queue.
* Throw IOException when collision is detected.

Add file Lock to avoid different actions on the same file.

---

.travis.yml
smart-metrics/src/main/java/org/smartdata/metrics/impl/MetricsFactory.java
smart-server/src/main/java/org/smartdata/server/metastore/tables/TableAddOpListener.java
smart-server/src/main/java/org/smartdata/server/rule/RuleQueryExecutor.java
smart-server/src/main/scala/org/smartdata/server/web/ActionService.scala
smart-server/src/test/java/org/smartdata/server/command/TestCommandDescriptor.java

try to fix code coverage

---

pom.xml
smart-alluxio/pom.xml
smart-alluxio/src/main/java/org/smartdata/actions/alluxio/AlluxioAction.java
smart-alluxio/src/main/java/org/smartdata/actions/alluxio/AlluxioActionType.java
smart-alluxio/src/main/java/org/smartdata/actions/alluxio/AlluxioCopyRunner.java
smart-alluxio/src/main/java/org/smartdata/client/alluxio/SmartAlluxioFileSystem.java

initialize the smart-alluxio module

initialize smart-alluxio module

---

smart-common/src/main/java/org/smartdata/common/command/CommandInfo.java
smart-server/src/main/java/org/smartdata/server/metastore/DruidPool.java
smart-server/src/main/java/org/smartdata/server/metastore/tables/ActionDao.java
smart-server/src/main/java/org/smartdata/server/metastore/tables/CommandDao.java
smart-server/src/test/java/org/smartdata/server/metastore/tables/TestActionDao.java
smart-server/src/test/java/org/smartdata/server/metastore/tables/TestCommandDao.java

* Add CommandDao with all command related methods in DBAdapter.
* Add ActionDao with all action related methods in DBAdapter.
* Add UTs for both Dao.

Add CommandDao, and enhance ActionDao

---

smart-server/src/main/java/org/smartdata/server/metastore/MetaStore.java
smart-server/src/main/java/org/smartdata/server/metastore/tables/AccessCountDao.java
smart-server/src/test/java/org/smartdata/server/metastore/TestDBMethod.java
smart-server/src/test/java/org/smartdata/server/metastore/TestMetaStore.java

* Rename MetaStoreHandle to MetaStore
* Remove unused methods.
* Add cache/map support.

Rename MetaStoreHandle to MetaStore

---

smart-server/src/test/java/org/smartdata/server/metastore/TestDaoUtil.java
smart-server/src/test/java/org/smartdata/server/metastore/TestMetaStore.java
smart-server/src/test/java/org/smartdata/server/metastore/tables/TestActionDao.java
smart-server/src/test/java/org/smartdata/server/metastore/tables/TestCacheFileDao.java
smart-server/src/test/java/org/smartdata/server/metastore/tables/TestCmdletDao.java
smart-server/src/test/java/org/smartdata/server/metastore/tables/TestFileDao.java
smart-server/src/test/java/org/smartdata/server/metastore/tables/TestOtherDao.java
smart-server/src/test/java/org/smartdata/server/metastore/tables/TestRuleDao.java
smart-server/src/test/java/org/smartdata/server/metastore/tables/TestStorageDao.java

* Modify TestDaoUtil.
* Simplify TestDaoUtil's subclasses.
* Add more UT from DBAdapter.

Modify TestDaoUtil and its subclasses.

---

smart-server/src/main/java/org/smartdata/server/metastore/MetaStore.java
smart-server/src/main/java/org/smartdata/server/metastore/tables/StorageDao.java
smart-server/src/test/java/org/smartdata/server/metastore/TestMetaStore.java

* Fix compile error.
* Fix map support.
* Fix storageDao related DB methods.

Fix storage, user and group map.

---

smart-server/src/main/java/org/smartdata/server/metastore/DBAdapter.java
smart-server/src/main/java/org/smartdata/server/metastore/MetaStore.java
smart-server/src/main/java/org/smartdata/server/metastore/MetaUtil.java
smart-server/src/main/java/org/smartdata/server/metastore/tables/FileDao.java
smart-server/src/test/java/org/smartdata/server/metastore/TestMetaStore.java
smart-server/src/test/java/org/smartdata/server/metastore/tables/TestFileDao.java

* Fix map support for fileDao.
* Fix fileDao related UT.

Fix fileDao and add map support.

---

smart-server/src/test/java/org/smartdata/server/engine/rule/TestRuleManager.java
smart-server/src/test/java/org/smartdata/server/engine/rule/TestSmartRuleParser.java
smart-server/src/test/java/org/smartdata/server/metastore/TestDBUtil.java
smart-server/src/test/java/org/smartdata/server/metastore/TestRulesTable.java
smart-server/src/test/java/org/smartdata/server/metastore/TestSqliteDB.java
smart-server/src/test/java/org/smartdata/server/metric/fetcher/TestCachedListFetcher.java

* Modify TestRulesTable with dataPool.
* Modify TestSqliteDB  with dataPool.
* Modify TestCachedListFetcher with dataPool.
* Modify TestRuleManager with dataPool.

Modify DBAdapter related UT.

---

smart-actions/src/main/java/org/smartdata/actions/ActionRegistry.java
smart-actions/src/main/java/org/smartdata/actions/SmartAction.java
smart-agent/src/main/java/org/smartdata/agent/SmartAgent.java
smart-common/src/main/java/org/smartdata/common/message/ActionStatusReport.java
smart-common/src/main/java/org/smartdata/common/message/CmdletStatusUpdate.java
smart-common/src/main/java/org/smartdata/common/message/StatusMessage.java
smart-common/src/main/java/org/smartdata/common/message/StatusReporter.java
smart-engine/src/main/java/org/smartdata/server/cluster/HazelcastWorker.java
smart-engine/src/main/java/org/smartdata/server/engine/CmdletManager.java
smart-engine/src/main/java/org/smartdata/server/engine/cmdlet/CmdletExecutor.java
smart-engine/src/main/java/org/smartdata/server/engine/cmdlet/HazelcastExecutorService.java
smart-engine/src/main/java/org/smartdata/server/engine/cmdlet/LocalCmdletExecutorService.java
smart-engine/src/main/java/org/smartdata/server/engine/cmdlet/agent/AgentMaster.java

@littlezhou is this interface OK for SmartAction?

add status reporter to SmartAction

---

.travis.yml
pom.xml
smart-alluxio/pom.xml
smart-alluxio/src/main/java/org/smartdata/actions/alluxio/FreeAction.java
smart-alluxio/src/main/java/org/smartdata/actions/alluxio/LoadAction.java
smart-alluxio/src/main/java/org/smartdata/actions/alluxio/PersistAction.java
smart-alluxio/src/main/java/org/smartdata/actions/alluxio/PinAction.java
smart-alluxio/src/main/java/org/smartdata/actions/alluxio/SetTTLAction.java
smart-alluxio/src/main/java/org/smartdata/actions/alluxio/UnpinAction.java
smart-alluxio/src/test/java/org/smartdata/actions/alluxio/TestAlluxioActions.java
smart-alluxio/src/test/resources/log4j.properties

1, add alluxio actions
2, introduce alluxio minicluster for test
3, add one unit test for persist action and tests for other actions to be added.

Add alluxio actions and introduce alluxio minicluster for test

---

smart-engine/src/main/java/org/smartdata/server/engine/CmdletExecutor.java
smart-server/src/test/java/org/smartdata/server/engine/cmdlet/TestCmdletExecutor.java

Add DeleteCmdlet by rule Id.

---

smart-alluxio/src/test/java/org/smartdata/actions/alluxio/TestAlluxioActions.java

Add unit tests for other alluxio actions

Add tests for alluxio actions

---

smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/test/java/org/smartdata/metastore/TestMetaStore.java
smart-metastore/src/test/resources/druid-template.xml
smart-metastore/src/test/resources/log4j.properties

* Add Concurrency Unit tests.
* Modify druid-template.xml.
* Add log support for metastore.

Add concurrency Unit tests and log support for metastore.

---

pom.xml
smart-integration/src/test/java/org/smartdata/integration/IntegrationTest.java
smart-metastore/pom.xml
smart-metastore/src/main/java/org/smartdata/metastore/tables/AccessCountTableAggregator.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/ActionDao.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/FileDao.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/GroupsDao.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/StorageDao.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/UserDao.java
smart-metastore/src/main/java/org/smartdata/metastore/utils/MetaUtil.java

* Add mysql support.
* Modify/fix sql or maps in dao.

Modify metastore for Mysql support.

---

pom.xml
smart-integration/src/test/java/org/smartdata/integration/IntegrationSmartServer.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStoreExecption.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/FileDao.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/FileInfoDao.java
smart-metastore/src/main/java/org/smartdata/metastore/utils/MetaStoreUtils.java
smart-metastore/src/main/java/org/smartdata/metastore/utils/TestDBUtil.java
smart-metastore/src/main/java/org/smartdata/metastore/utils/TestDaoUtil.java
smart-metastore/src/test/java/org/smartdata/metastore/TestDruid.java
smart-metastore/src/test/java/org/smartdata/metastore/TestSqliteDB.java
smart-metastore/src/test/resources/druid-template.xml
smart-server/src/main/java/org/smartdata/server/SmartServer.java
smart-server/src/test/java/org/smartdata/server/TestEmptyMiniSmartCluster.java
smart-server/src/test/java/org/smartdata/server/TestSmartServer.java
smart-server/src/test/java/org/smartdata/server/TestSmartServerCli.java
smart-server/src/test/java/org/smartdata/server/TestSmartServerLogin.java
smart-server/src/test/java/org/smartdata/server/TestSmartServerReConfig.java

* Rename MetaUtil to MetaStoreUtils. 
* Fix a problem casued by mysql-connector 6.0 .

Enhance mysql support.

---

smart-alluxio/src/main/java/org/smartdata/alluxio/metric/fetcher/AlluxioNamespaceFetcher.java
smart-engine/src/main/java/org/smartdata/server/engine/CmdletExecutor.java
smart-engine/src/main/java/org/smartdata/server/engine/CmdletManager.java
smart-engine/src/main/java/org/smartdata/server/engine/RuleManager.java
smart-engine/src/main/java/org/smartdata/server/engine/StatesManager.java
smart-engine/src/main/java/org/smartdata/server/engine/rule/RuleExecutor.java
smart-engine/src/main/java/org/smartdata/server/engine/rule/RuleInfoRepo.java
smart-hdfs/src/main/java/org/smartdata/hdfs/HdfsStatesUpdaterService.java
smart-hdfs/src/main/java/org/smartdata/hdfs/metric/fetcher/CachedListFetcher.java
smart-hdfs/src/main/java/org/smartdata/hdfs/metric/fetcher/InotifyEventApplier.java
smart-hdfs/src/main/java/org/smartdata/hdfs/metric/fetcher/InotifyEventFetcher.java
smart-hdfs/src/main/java/org/smartdata/hdfs/metric/fetcher/InotifyFetchAndApplyTask.java
smart-hdfs/src/main/java/org/smartdata/hdfs/metric/fetcher/NamespaceFetcher.java
smart-hdfs/src/test/java/org/smartdata/hdfs/metric/fetcher/TestNamespaceFetcher.java
smart-metastore/src/main/java/org/smartdata/metastore/DruidPool.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStoreException.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/AccessCountTableAggregator.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/AccessCountTableManager.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/AccessEventAggregator.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/TableAddOpListener.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/TableEvictor.java
smart-metastore/src/main/java/org/smartdata/metastore/utils/MetaStoreUtils.java
smart-metastore/src/main/java/org/smartdata/metastore/utils/TestDBUtil.java
smart-metastore/src/test/java/org/smartdata/metastore/TestMetaStore.java
smart-metastore/src/test/java/org/smartdata/metastore/TestSqliteDB.java
smart-metastore/src/test/java/org/smartdata/metastore/tables/TestAccessCountTableManager.java
smart-metastore/src/test/java/org/smartdata/metastore/tables/TestAccessEventAggregator.java
smart-server/src/test/java/org/smartdata/server/engine/TestCmdletManager.java

Replace SQLException with Metastore Exception.

Add support to MetastoreException

---

smart-alluxio/src/main/java/org/smartdata/alluxio/metric/fetcher/AlluxioNamespaceFetcher.java
smart-alluxio/src/test/java/org/smartdata/actions/alluxio/metric/fetcher/TestAlluxioNamespaceFetcher.java
smart-hdfs/src/main/java/org/smartdata/hdfs/metric/fetcher/NamespaceFetcher.java
smart-hdfs/src/test/java/org/smartdata/hdfs/metric/fetcher/TestNamespaceFetcher.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/fetcher/FetchTask.java
smart-metastore/src/main/java/org/smartdata/metastore/fetcher/FileInfoBatch.java
smart-metastore/src/main/java/org/smartdata/metastore/fetcher/FileStatusConsumer.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/FileDao.java

1, extract FileStatusConsumer to metastore
2, extract FileStatusInternalBatch to metastore as FileInfoBatch 
3, extract common code in FetchTask to abstract class FetchTask
4, use FileInfo instead of FileStatusInternal in NamespaceFetcher

Extract common code in NamespaceFetcher from alluxio and hdfs

---

smart-metastore/src/main/java/org/smartdata/metastore/tables/ActionDao.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/CmdletDao.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/FileDao.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/FileInfoDao.java

Add a new way to branch insert for matastore.

Batch Insert improvement

---

smart-hdfs/src/test/java/org/smartdata/hdfs/metric/fetcher/TestInotifyEventApplier.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/FileDao.java
smart-metastore/src/main/java/org/smartdata/metastore/tables/ManagementDao.java
smart-metastore/src/test/java/org/smartdata/metastore/tables/TestFileDao.java

* Remove QueryHelper.
* Fix exceptions caused by corner cases, e.g. empty actions/files tables.

Add management dao

---

docs/overall-initiative.md

@taojieterry would you review this? Thanks!

Added to mention the Alluxio support

---

smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/MetaStoreHelper.java
smart-metastore/src/main/java/org/smartdata/metastore/utils/MetaStoreUtils.java

* Rename managementDao to MetaStoreHelper.
* Imporve dropallTablesMysql.

Rename managementDao to MetaStoreHelper. 

---

smart-engine/src/main/java/org/smartdata/server/engine/rule/RuleExecutor.java
smart-engine/src/test/java/org/smartdata/server/engine/rule/TestRuleExecutor.java
smart-engine/src/test/java/org/smartdata/server/engine/rule/testRuleExecutor.java
smart-engine/src/test/resources/druid-template.xml
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/MetaStoreHelper.java

* Fix a aggregate SQL problem in mysql.
* Move dropTable and dropView to MetaStoreHelper.

Fix union sql error on mysql

---

smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/ActionDao.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/CmdletDao.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/FileDao.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/FileInfoDao.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestFileDao.java

* Fix a error in FileDao.insert.
* Remove unnecessary code in *Dao.

Fix wrong file sid

---

smart-common/src/main/java/org/smartdata/model/CachedFileStatus.java
smart-common/src/main/java/org/smartdata/model/StorageCapacity.java
smart-common/src/main/java/org/smartdata/model/StoragePolicy.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/StorageDao.java
smart-metastore/src/test/java/org/smartdata/metastore/TestMetaStore.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestCacheFileDao.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestStorageDao.java

* Add equal and hashCode to StoragePolicy, StorageCapacity and CachedFileStatus.
* Modify Assert in TestCacheFileDao and TestStorageDao.

Modify/check TestCacheFileDao and TestStorageDao with equal.

---

smart-server/src/main/dashboard/services/models/models.js

This is a work-around but I think it would suffice.

fix action runtime in dashboard

---

smart-actions/src/main/java/org/smartdata/actions/SmartAction.java
smart-admin/src/main/java/org/smartdata/admin/tools/RuleCmdlets.java
smart-agent/src/main/java/org/smartdata/agent/SmartAgent.java
smart-engine/src/main/java/org/smartdata/server/cluster/HazelcastWorker.java
smart-engine/src/main/java/org/smartdata/server/engine/CmdletManager.java
smart-engine/src/main/java/org/smartdata/server/engine/cmdlet/CmdletExecutor.java
smart-engine/src/main/java/org/smartdata/server/engine/cmdlet/CmdletFactory.java
smart-engine/src/main/java/org/smartdata/server/engine/cmdlet/LocalCmdletExecutorService.java
smart-engine/src/main/java/org/smartdata/server/engine/data/AccessEventFetcher.java
smart-engine/src/main/java/org/smartdata/server/engine/rule/RuleInfoRepo.java
smart-hdfs/src/main/java/org/smartdata/hdfs/metric/fetcher/InotifyEventFetcher.java
smart-hdfs/src/main/java/org/smartdata/hdfs/metric/fetcher/InotifyFetchAndApplyTask.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/TableAddOpListener.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/TableEvictor.java
smart-metrics/src/main/java/org/smartdata/metrics/impl/SmartServerAccessEventSource.java
smart-metrics/src/main/java/org/smartdata/metrics/impl/hdfs/NNMetricsAccessEventCollector.java
smart-server/src/main/java/org/smartdata/server/SmartServer.java
smart-zeppelin/zeppelin-server/src/main/java/org/apache/zeppelin/rest/NotebookRestApi.java

* Replace PrintStack with Log to aggregate logs into logs dir.
* Fix a bug in rule which makes check number incorrect.

Replace Printstack with Log

---

smart-engine/src/main/java/org/smartdata/server/engine/cmdlet/HazelcastExecutorService.java
smart-engine/src/main/java/org/smartdata/server/engine/rule/RuleExecutor.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/AccessCountDao.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/AccessCountTable.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/AccessCountTableManager.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestAccessCountTableManager.java
smart-server/src/main/java/org/smartdata/server/SmartDaemon.java
smart-zeppelin/zeppelin-web/src/app/dashboard/views/actions/actions.js
smart-zeppelin/zeppelin-web/src/app/dashboard/views/rules/rules.js
smart-zeppelin/zeppelin-web/src/app/dashing/property/property.html

1.add button to phglyphicon
2."start" and "stop" button combine into one

Change button style of rules

---

smart-actions/src/main/java/org/smartdata/actions/hdfs/CopyFileAction.java
smart-actions/src/main/java/org/smartdata/actions/hdfs/ReadFileAction.java
smart-actions/src/test/java/org/smartdata/actions/hdfs/TestCopyFileAction.java

Copy single file from src to dist.

CopyFileAction for Single File

---

smart-actions/src/main/java/org/smartdata/actions/hdfs/CopyFileAction.java
smart-actions/src/main/java/org/smartdata/actions/hdfs/HdfsActionFactory.java
smart-actions/src/test/java/org/smartdata/actions/hdfs/TestCopyFileAction.java

* Remove dir copy code.
* Enhance remote copy.

Make CopyFileAction foucses on single file copy.

---

smart-engine/src/main/java/org/smartdata/server/engine/CopyScheduler.java
smart-server/src/test/java/org/smartdata/server/TestCopySchedular.java

* Add forceSync method.
* Modify TestCopySchedular with TestEmptyMiniSmartCluster.

Add forceSync method, and modify TestCopySchedular

---

smart-common/src/main/java/org/smartdata/model/DataNodeInfo.java
smart-common/src/main/java/org/smartdata/model/DataNodeStorageInfo.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/DataNodeInfoDao.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/DataNodeStorageInfoDao.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestDataNodeInfoDao.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestDataNodeStorageInfoDao.java

#820 Implement Entity and Dao of DataInfo & DataStorageInfo to store/get datanode info from database

#820 Implement Entity and Dao of DataInfo & DataStorageInfo to store/get datanode info from database

---

smart-erasurecode/pom.xml
smart-erasurecode/smart-erasurecodec/README.md
smart-erasurecode/smart-erasurecodec/pom.xml
smart-erasurecode/smart-erasurecodec/src/CMakeLists.txt
smart-erasurecode/smart-maven-plugins/README.md
smart-erasurecode/smart-maven-plugins/pom.xml
smart-erasurecode/smart-maven-plugins/src/main/java/org/smartdata/maven/plugin/cmakebuilder/CompileMojo.java
smart-erasurecode/smart-maven-plugins/src/main/java/org/smartdata/maven/plugin/cmakebuilder/TestMojo.java
smart-erasurecode/smart-maven-plugins/src/main/java/org/smartdata/maven/plugin/util/Exec.java

Smart-maven-plugins is used to compile native erasure code.
It can be installed and used without extra operations.

Smart-maven-plugins

---

smart-engine/src/main/java/org/smartdata/server/engine/CentralizedCopyScheduler.java
smart-engine/src/main/java/org/smartdata/server/engine/CmdletManager.java
smart-engine/src/main/java/org/smartdata/server/engine/CopyScheduler.java
smart-engine/src/main/java/org/smartdata/server/engine/cmdlet/Cmdlet.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/FileDiffDao.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestFileDiffDao.java
smart-server/src/test/java/org/smartdata/server/TestCopySchedular.java

* Add new CopyScheduler.
* Fix TestCopyScheduler.

New copy scheduler

---

smart-common/src/main/java/org/smartdata/model/FileDiff.java
smart-common/src/main/java/org/smartdata/model/FileDiffState.java
smart-engine/src/main/java/org/smartdata/server/engine/CentralizedCopyScheduler.java
smart-engine/src/main/java/org/smartdata/server/engine/CopyScheduler.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/metric/fetcher/InotifyEventApplier.java
smart-hadoop-support/smart-hadoop/src/test/java/org/smartdata/hdfs/metric/fetcher/TestInotifyEventApplier.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/FileDiffDao.java
smart-metastore/src/main/java/org/smartdata/metastore/utils/MetaStoreUtils.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestFileDiffDao.java
smart-server/src/test/java/org/smartdata/server/TestCopySchedular.java

* Replace `applied` field with `state` (Currently three states: PENDING, RUNNING, APPLIED). 
* Add ruleId (rid) for rule based filter.
* Add todos to CopyScheduler.

Fix #907, modify file_diff table and dao

---

smart-hadoop-support/smart-hadoop-2.7/src/test/java/org/smartdata/hdfs/action/TestMoveFileAction.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/move/MoverExecutor.java

#882 Add unit tests for move file actions

#882 Add unit tests for move file actions 

---

smart-metastore/src/main/java/org/smartdata/metastore/dao/ActionDao.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestActionDao.java
smart-zeppelin/zeppelin-server/src/main/java/org/smartdata/server/rest/ActionRestApi.java

* Enhance actionDao
* Add list all actions support for UI. if size = 0, getLatestActions will return all actions.

Add list all actions support for UI

---

supports/integrate-test/test_mover_protection.py

I test mover while doing delete, overwrite, read as well as append

Rewrite integrate

---

smart-common/src/main/java/org/smartdata/model/FileDiff.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/metric/fetcher/InotifyEventApplier.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/FileInfoDao.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestFileInfoDao.java

* Add getFilesByPrefix for searching all related files under given directory.
* Add more methods to filechain.
* Refine forceSync based on file table rather than HDFS filesystem.
* Refine fileDiff generator in InotifyEventApplier.

Add getFilesByPrefix for searching all files under given directory

---

smart-engine/src/main/java/org/smartdata/server/engine/CmdletManager.java
smart-integration/src/test/java/org/smartdata/integration/TestActionRestApi.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-zeppelin/zeppelin-server/src/main/java/org/smartdata/server/rest/ActionRestApi.java

* New restful api url is  `/type/{listNumber}/{actionName}`

Add listActionsByType Restful API support

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java

* Rewrite forceSync based on file table
* Integrate CopyScheduler with cmdletManager.

Finish forceSync based on file table

---

smart-common/src/main/java/org/smartdata/SmartConstants.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/metric/fetcher/InotifyEventApplier.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java
smart-hadoop-support/smart-hadoop/src/test/java/org/smartdata/hdfs/metric/fetcher/TestInotifyEventApplier.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/ActionDao.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/CmdletDao.java
smart-server/src/test/java/org/smartdata/server/TestCopyScheduler.java

* Integrate CopyScheduler with cmdletManager
* Add deleteAll method for fileInfo, fileDiff, action and cmdlet

Integrate CopyScheduler with cmdletManager

---

smart-engine/src/main/java/org/smartdata/server/engine/CmdletManager.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-zeppelin/zeppelin-server/src/main/java/org/smartdata/server/rest/ActionRestApi.java

* Add list actions by rid restful api `/actions/list/{listNumber}/{ruleId}`

Add list actions by rid restful api

---

smart-common/src/main/java/org/smartdata/metaservice/BackupMetaService.java
smart-common/src/main/java/org/smartdata/model/DetailedRuleInfo.java
smart-engine/src/main/java/org/smartdata/server/engine/RuleManager.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/BackUpInfoDao.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/FileDiffDao.java
smart-metastore/src/test/java/org/smartdata/metastore/TestMetaStore.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestBackUpInfoDao.java
smart-zeppelin/zeppelin-server/src/main/java/org/smartdata/server/rest/RuleRestApi.java

* List Sync rule: `/rules/list/move`
* List Move rule: `/rules/list/sync`
#923 #924 
Return DetailedRuleInfo.

List Move ans Sync rule restful api

---

smart-common/src/main/java/org/smartdata/SmartContext.java
smart-common/src/main/java/org/smartdata/conf/SmartConfKeys.java
smart-engine/src/main/java/org/smartdata/server/SmartEngine.java
smart-engine/src/main/java/org/smartdata/server/engine/AbstractServiceFactory.java
smart-engine/src/main/java/org/smartdata/server/engine/ServerContext.java
smart-engine/src/main/java/org/smartdata/server/engine/ServiceMode.java
smart-server/src/main/java/org/smartdata/server/SmartServer.java

Added a configuration smart.service.mode to indicate whether ssm is on hdfs or alluxio.

support config smart.service.mode

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java
smart-server/src/test/java/org/smartdata/server/TestCopyScheduler.java

* Fix fileDiff state sync problem

Fix filediff state sync

---

smart-alluxio-support/smart-alluxio/pom.xml
smart-alluxio-support/smart-alluxio/src/main/java/org/smartdata/alluxio/AlluxioUtil.java
smart-alluxio-support/smart-alluxio/src/main/java/org/smartdata/alluxio/action/AlluxioActionFactory.java
smart-alluxio-support/smart-alluxio/src/main/java/org/smartdata/alluxio/action/FreeAction.java
smart-alluxio-support/smart-alluxio/src/main/java/org/smartdata/alluxio/action/LoadAction.java
smart-alluxio-support/smart-alluxio/src/main/java/org/smartdata/alluxio/action/PersistAction.java
smart-alluxio-support/smart-alluxio/src/main/java/org/smartdata/alluxio/action/SetTTLAction.java
smart-alluxio-support/smart-alluxio/src/main/java/org/smartdata/alluxio/action/UnpinAction.java
smart-alluxio-support/smart-alluxio/src/main/resources/META-INF/services/org.smartdata.action.ActionFactory
smart-common/src/main/java/org/smartdata/SmartContext.java
smart-common/src/main/java/org/smartdata/conf/SmartConfKeys.java
smart-engine/pom.xml
smart-engine/src/main/java/org/smartdata/server/SmartEngine.java
smart-engine/src/main/java/org/smartdata/server/engine/AbstractServiceFactory.java
smart-engine/src/main/java/org/smartdata/server/engine/ServerContext.java
smart-engine/src/main/java/org/smartdata/server/engine/ServiceMode.java
smart-engine/src/main/java/org/smartdata/server/engine/cmdlet/CmdletFactory.java
smart-server/src/main/java/org/smartdata/server/SmartServer.java

now alluxio actions is able to run in ssm

enable alluxio actions

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java
smart-server/src/test/java/org/smartdata/server/TestCopyScheduler.java

* Remove duplicate actions.
* Add Delete sync action trigger UT.

Remove duplicate actions

---

smart-common/src/main/java/org/smartdata/model/DetailedFileAction.java
smart-common/src/main/java/org/smartdata/model/DetailedRuleInfo.java
smart-engine/src/main/java/org/smartdata/server/engine/CmdletManager.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-zeppelin/zeppelin-server/src/main/java/org/smartdata/server/rest/ActionRestApi.java

* Add listFileActions in Metastore
* Add Action restful API `/filelist/{listNumber}/{ruleId}`

Add list file actions for mover and copy

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java
smart-server/src/test/java/org/smartdata/server/TestCopyScheduler.java

* Fix rename sync file action fails.

Fix rename Sync action

---

smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/FileDiffDao.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestFileDiffDao.java

* Fix wrong run progress in sync rule
* Fix action display in sync and mover action page

Fix action display in sync and mover action page

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/AppendFileAction.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/CopyFileAction.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/HdfsActionFactory.java
smart-hadoop-support/smart-hadoop/src/test/java/org/smartdata/hdfs/action/TestAppendFileAction.java
smart-hadoop-support/smart-hadoop/src/test/java/org/smartdata/hdfs/action/TestCopyFileAction.java
smart-hadoop-support/smart-hadoop/src/test/java/org/smartdata/hdfs/action/TestWriteFileAction.java

* Add CopyFileAction Append Support
* Refine AppendFileAction and UT
* Add UT for remote copy and append

Add CopyFileAction Append Support

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/CopyFileAction.java

* Read Replication from remote default configuration
* Make sure remote replication is correct

Fix CopyFileAction Replication Problem

---

smart-common/src/main/java/org/smartdata/metaservice/BackupMetaService.java
smart-common/src/main/java/org/smartdata/model/FileDiffType.java
smart-engine/src/main/java/org/smartdata/server/engine/rule/FileCopyDrPlugin.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/metric/fetcher/InotifyEventApplier.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java
smart-hadoop-support/smart-hadoop/src/test/java/org/smartdata/hdfs/metric/fetcher/TestInotifyEventApplier.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/test/java/org/smartdata/metastore/TestMetaStore.java

* Enable Inotify filter based on backup_file table
* Add Metadata support in Inotify applier

Enable Inotify filter based on backup_file table

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/metric/fetcher/InotifyEventApplier.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/test/java/org/smartdata/metastore/TestMetaStore.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestBackUpInfoDao.java

* Fix Backup filter bug
* Enhance Delete Diffs
* Add UT for new MetaStore.srcInbackup

Fix Backup filter bug, enhance Delete Diffs

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/utils/MetaStoreUtils.java
smart-server/src/test/java/org/smartdata/server/TestCopyScheduler.java

* Fix an exception in CopyScheduler, which may cause an unexpected exist
* Add index to file_diff table.src
* Add fileDiffMap to avoid duplicate file_diff apply
* Add Timeout in UT

Fix a bug in CopyScheduler, which may cause an unexpected exist

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/AppendFileAction.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/CopyFileAction.java
smart-hadoop-support/smart-hadoop/src/test/java/org/smartdata/hdfs/MiniClusterHarness.java
smart-hadoop-support/smart-hadoop/src/test/java/org/smartdata/hdfs/action/TestCopyFileAction.java

* Let AppendFileAction and CopyFileAction read local HDFS conf from SmartContext.
* Enable TestCopyFileAction UT.

Let AppendFileAction and CopyFileAction read local HDFS conf from SmartContext

---

smart-engine/src/main/java/org/smartdata/server/engine/rule/FileCopyDrPlugin.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/metric/fetcher/InotifyEventApplier.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java
smart-server/src/test/java/org/smartdata/server/TestCopyScheduler.java

* Remove access_time from meta diff.
* Fix deleteMerge UT.

Remove access_time from meta diff

---

smart-engine/src/main/java/org/smartdata/server/engine/rule/FileCopyDrPlugin.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/metric/fetcher/InotifyEventApplier.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java
smart-server/src/test/java/org/smartdata/server/TestCopyScheduler.java

* Fix a deadlock caused by failed meta diff.
* Refine MetaDataAction parameter names.

Fix a deadlock caused by failed meta diff

---

smart-engine/src/main/java/org/smartdata/server/SmartEngine.java
smart-engine/src/main/java/org/smartdata/server/engine/StatesManager.java

Add restApi support to get storage usage

---

smart-engine/src/main/java/org/smartdata/server/engine/CmdletManager.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/CopyFileAction.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java

* Fix scheduler.FAIL action problem.
* Add logs in CopyFileAction.
* Add one more condition check in Sync Action Submission check.

Fix scheduler.FAIL action problem

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java

* Enable batch (batch size = 300) insert for baseSync.
* Refine Logs.

Enable batch insert for baseSync

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/metric/fetcher/CachedListFetcher.java

fix the bug in cachelistfetcher

fix the bug in 'cachelistfetcher'

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java

* Remove logs in std.out.
* Change some logs from info to debug.
* Add more debug logs.

Fix #1220, refine logger output in CopyScheduler

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/FileDiffDao.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestFileDiffDao.java
smart-server/src/test/java/org/smartdata/server/TestCopyScheduler.java

add functions to support FileDiff memory cache

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java

* Fix merge methods in CopyScheduler.
* Fix a sync bug in batchDirectSync.

Fix merge methods in CopyScheduler

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/CopyFileAction.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java

* Fix baseSync and remote check. Refine remote check to reduce network traffic.
* Remove CopyFileAction overwrite. Because offset = 0 means overwrite.

Fix baseSync and remote check

---

pom.xml
smart-action/pom.xml
smart-common/pom.xml
smart-dist/pom.xml
smart-engine/pom.xml
smart-hadoop-support/smart-erasurecodec/pom.xml
smart-integration/src/test/java/org/smartdata/integration/util/Util.java
smart-maven-plugins/pom.xml
smart-zeppelin/zeppelin-display/pom.xml
smart-zeppelin/zeppelin-distribution/pom.xml
smart-zeppelin/zeppelin-interpreter/pom.xml
smart-zeppelin/zeppelin-server/pom.xml
smart-zeppelin/zeppelin-zengine/pom.xml
smart-zeppelin/zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/repo/AzureNotebookRepo.java
smart-zeppelin/zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/repo/S3NotebookRepo.java

This change will cause runtime issue. Need to further test the pull request.

Revert "Clean unused dependencies"

---

conf/smart-site.xml
smart-common/src/main/java/org/smartdata/conf/SmartConfKeys.java
smart-integration/src/test/java/org/smartdata/integration/IntegrationTestBase.java
smart-server/src/main/java/org/smartdata/server/SmartServer.java
smart-zeppelin/zeppelin-server/src/main/java/org/apache/zeppelin/server/SmartZeppelinServer.java

Remove two unnecessary properties

Remove smart.zeppelin.web.enable and smart.zeppelin.enable

---

smart-metrics/pom.xml
smart-metrics/src/main/java/org/smartdata/metrics/FileAccessEventSource.java
smart-metrics/src/main/java/org/smartdata/metrics/impl/MetricsFactory.java
smart-metrics/src/main/java/org/smartdata/metrics/impl/SmartServerAccessEventCollector.java
smart-metrics/src/main/java/org/smartdata/metrics/impl/SmartServerAccessEventSource.java
supports/tools/checkstyle.xml
supports/tools/suppressions.xml

Need to enable check-style step by step since the change will be quite huge.

Enable checkstyle for smart-metrics module

---

smart-metastore/src/main/java/org/smartdata/metastore/utils/MetaStoreUtils.java

Fix "Specified key was too long" issue in MySQL version 5.6 (and prior versions). The index size will be set to 750 in these versions, which will not effect the performance of general cases.

Fix "Specified key was too long" issue

---

smart-metastore/src/main/java/org/smartdata/metastore/utils/MetaStoreUtils.java

* Avoid setting  index length issue on `bigint` and `int`

Fix init-ssm.sh

---

smart-zeppelin/zeppelin-server/pom.xml

Remove dependency of javax to avoid conflict definition with javax in jersey-core

Fix UriBuilder exception

---

supports/How_TO_RUN.md
supports/integration-test/Disaster_Recovery_Performance_Test.md
supports/integration-test/reset_env.py
supports/integration-test/util.py

* Add Disaster Recovery test document.
* Add create random method in test script.

Add Disaster Recovery test document

---

smart-engine/src/main/java/org/smartdata/server/engine/CmdletManager.java
smart-zeppelin/zeppelin-server/src/main/java/org/smartdata/server/rest/ActionRestApi.java
smart-zeppelin/zeppelin-server/src/main/java/org/smartdata/server/rest/RuleRestApi.java

* Add `/filelist/{ruleId}/{pageIndex}/{numPerPage}` for data sync.
* Add `/{ruleId}/cmdlets/{pageIndex}/{numPerPage}/{orderBy}/{isDesc}` for user rule.

Add new restful APIs for data sync and rule detailed page support

---

smart-engine/src/main/java/org/smartdata/server/engine/CmdletManager.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java

* Fix total number = 0 bug.
* Fix some typo and code style.

Hotfix for getFileActions

---

smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/CmdletDao.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestCmdletDao.java

* Speed up fetching total number of files.

Solve #1375, speed up data sync page

---

smart-common/src/main/java/org/smartdata/model/FileDiffState.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java

* Fix unnecessary sync actions caused by dirty cache. Enhance file lock and improve cache sync method.
* Code refine and add comments.

Fix unnecessary sync actions caused by dirty cache

---

smart-common/src/main/java/org/smartdata/model/FileDiffState.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java

* Fix duplicate sync actions in data Sync.
* Improve performance of CopyScheduler.

Patch from trunk: Fix duplicate sync actions in data Sync 

---

smart-hadoop-support/smart-hadoop-2.7/src/main/java/org/smartdata/hdfs/CompatibilityHelper27.java
smart-hadoop-support/smart-hadoop-cdh-2.6/src/main/java/org/smartdata/hdfs/CompatibilityHelper26.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/CompatibilityHelper.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/Copy2S3Action.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/CopyFileAction.java
smart-hadoop-support/smart-hadoop/src/test/java/org/smartdata/hdfs/action/TestCopyFileAction.java

* Add s3 support for CopyFileAction.
* Add a new Copy2S3Action for copying the whole file to S3.

Add s3 Action Support

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/ReadFileAction.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-metastore/src/main/java/org/smartdata/metastore/dao/FileDiffDao.java
smart-metastore/src/test/java/org/smartdata/metastore/dao/TestFileDiffDao.java
smart-server/src/test/java/org/smartdata/server/TestCopyScheduler.java

* Fix baseSync crash after adding cache.
* Fix diff merge methods.
* Fix a log format in ReadFileAction.

Fix baseSync crash after restart rule

---

supports/integration-test/README.md
supports/integration-test/reset_env.py
supports/integration-test/test_rule.py
supports/integration-test/test_stress_rule.py
supports/integration-test/util.py

* Replace "/test/" with "/ssmtest/" for HDFS test directory.
* Add create 100M and 500K 0KB files script in `reset_env.py`.

 Use "/ssmtest/" as HDFS test directory, add scalability script

---

docs/disaster-recovery.md
docs/ssm-deployment-guide.md

* Add namespace fetcher batch size to deploy-guide.
* Fix typo.

Add namespace fetcher batch size to deploy-guide

---

supports/integration-test/reset_env.py
supports/integration-test/test_S3_1MB.py
supports/integration-test/test_stress_sync_10MB.py
supports/integration-test/test_stress_sync_1MB.py
supports/integration-test/util.py

* Fix code style of test script.
* Fix a bug in util.py

Fix code style of test script 

---

smart-engine/src/main/java/org/smartdata/server/engine/RuleManager.java
smart-engine/src/main/java/org/smartdata/server/engine/rule/FileCopy2S3Plugin.java
smart-hadoop-support/smart-hadoop-2.7/src/test/java/org/smartdata/hdfs/action/TestCopy2S3Action.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/Copy2S3Action.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/HdfsActionFactory.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/Copy2S3Scheduler.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java

* Fix dest path issue in copy2s3 related rule.
* Add Truncate0 to action list.
* Code style.

Solve #1519 , fix dest path issue in copy2s3 related rule

---

supports/integration-test/test_small_file.py
supports/integration-test/test_stress_sync_10MB.py
supports/integration-test/test_stress_sync_1MB.py
supports/integration-test/util.py

*  Add small file test script.
* Add `compact_small_file` method in `util.py`.

 Add small file test script

---

smart-engine/src/main/java/org/smartdata/server/engine/rule/FileCopy2S3Plugin.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/Copy2S3Scheduler.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/CopyScheduler.java

* Change unnecessary log from INFO to DEBUG.

Reduce INFO log in Data Sync

---

smart-zeppelin/zeppelin-server/pom.xml

Fix zeppelin-server/pom

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/Truncate0Action.java
smart-hadoop-support/smart-hadoop/src/test/java/org/smartdata/hdfs/action/TestTruncate0Action.java

add setXattr to truncate0

---

docs/ssm-deployment-guide.md

Add the detailed steps for integrating SSM to Apache Hadoop and CDH and fixed some typos.

Enhance the SSM deployment guide document.

---

docs/s3-support.md

* Add more details for performance issue.
* Add solution for dependencies on Hadoop-2.7.3.

Add trouble shooting for performance and dependencies

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/Copy2S3Action.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/WriteFileAction.java

* Fix bufSize usage in Copy2S3Action.
* Reorder parameters in WriteFileAction.

Fix bufSize usage in Copy2S3Action

---

smart-common/src/main/java/org/smartdata/SmartConstants.java
smart-common/src/main/java/org/smartdata/model/S3FileState.java
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/scheduler/Copy2S3Scheduler.java
smart-metastore/src/main/java/org/smartdata/metastore/MetaStore.java
smart-server/src/test/java/org/smartdata/server/TestCopy2S3Scheduler.java

* Add TestCopy2S3Scheduler.
* Fix Copy2S3Scheduler not registered issue in SmartConstants.
* Enhance duplication and fileState check in Copy2S3Scheduler.
Thanks @aurorahunter

Solve #1621, fix duplicate copying issue for Copy2S3Action

---

docs/ssm-deployment-guide.md

Update deployment guide for YARN access SSM jars, fix the classpath problem of MAPREDUCE job.

For issue #1686,  update deployment guide for YARN access SSM jars

---

smart-server/src/test/java/org/smartdata/server/TestCopy2S3Scheduler.java

Fix a possible assert error in TestCopy2S3Scheduler.testDir

Solve #1691, fix TestCopy2S3Scheduler.testDir

---

smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/action/HdfsActionFactory.java

If truncate action not added,  it cannot be recognized.

Add truncate action in HdfsActionFactory

---

supports/integration-test/ssm_generate_test_data.py
supports/integration-test/test_small_file_actions.py
supports/integration-test/test_small_file_rule.py
supports/integration-test/test_smart_file_system.py
supports/integration-test/util.py

Updated from PR[#1781](https://github.com/Intel-bigdata/SSM/pull/1781#discussion_r192585364)# to solve conflicts.

Update Test Small File Scripts

---

conf/log4j.properties
smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/metric/fetcher/MovePlanMaker.java

* Change log level of org.apache.hadoop.io.retry.RetryInvocationHandler to ERROR. This will downgrade HA, failover and retry related log.

Downgrade HA & failover related log
